// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kojqbznueyahoybqgueh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvanFiem51ZXlhaG95YnFndWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0OTc5ODgsImV4cCI6MjA1NzA3Mzk4OH0._TCVNS1lAc7R4QRRcpRI11ZexdUNwbH6Ky0ZHN2HU4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);